#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Customize to your needs...

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/logan/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/home/logan/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/logan/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/logan/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

PATH="${PATH}:/snap/bin"
PATH="${PATH}:/home/logan/bin"

alias sd="sudo docker "
#alias az="azure-cli "

gittags() {
  git tag -l "$1/*" --sort -v:refname | head -10
}

#id16879 start
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

autoload -Uz promptinit
promptinit
prompt powerlevel10k
#id16879 end

alias vi="nvim "
