# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Customize to your needs...

PATH="${PATH}:/snap/bin"
PATH="${PATH}:/home/logan/bin"

alias sd="sudo docker "
#alias az="azure-cli "

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

autoload -Uz promptinit
promptinit
prompt powerlevel10k

alias vi="nvim "
alias gitlatest='git for-each-ref --sort=-committerdate refs/heads/ | head'
alias gdiff='git diff --color-moved=blocks '
alias gdiffc='git diff --cached --color-moved=blocks '
bindkey -v

source <(fzf --zsh)
alias vif='vi $(fzf) '
. "$HOME/.cargo/env"

. "$HOME/.local/bin/env"
